---
common_timezone: America/Montreal
common_deploy_user: deploy
common_deploy_user_shell: /bin/bash

common_packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - unzip
  - jq
  - net-tools
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - fail2ban
  - unattended-upgrades
  - logrotate

common_sysctl_hardening:
  net.ipv4.ip_forward: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.accept_source_route: 0
  net.ipv4.conf.all.log_martians: 1
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.tcp_syncookies: 1
  kernel.randomize_va_space: 2
